Resources:
  LambdaExecutionRoleTranscribe:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        - PolicyName: TranscribePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - transcribe:StartTranscriptionJob
                Effect: Allow
                Resource: "*"
        - PolicyName: TranscribeLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: PassRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - iam:PassRole
                Effect: Allow
                Resource: !GetAtt TranscribeDataAccessRole.Arn

  LambdaExecutionRoleSummarize:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        - PolicyName: BedrockInvocationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - bedrock:InvokeModel
                Effect: Allow
                Resource: "*"
        - PolicyName: SummarizeLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: SummarizeS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - arn:aws:s3:::${self:custom.transcriptBucket}/*

  TranscribeDataAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: transcribe.amazonaws.com
      Policies:
        - PolicyName: TranscribeAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - arn:aws:s3:::${self:custom.meetingBucket}/*
                  - arn:aws:s3:::${self:custom.transcriptBucket}/*